### ISSUE TITLE
Not working with JavaScript / CSS Asset Management enabled

### ISSUE THREAD

**Issue by bcutter** [icewind1991/logreader#12]
As soon as "JavaScript and CSS Asset Management" is activated in OwnCloud, the Logreader page does not load anymore.

Configured it using https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/js_css_asset_management_configuration.html and everything worked fine - EXCEPT Logreader, which isn´t loaded anymore (white page). If I disable the 'asset-pipeline.enabled' in config.php Logreader works again.

I guess that´s the reason for the "It is not recommended to enable asset-pipelining when using apps pulled via git." on the official OC documentation (see link above).

Can you "make it work" with JS / CSS Asset Management? Only Logreader keeps me away from activating this performance setting!

**Comment by Rickowski** [comment]
Same here. The app won't work anymore with
'asset-pipeline.enabled' => true,
set in config.

**Comment by icewind1991** [comment]
Fixed with #e8627cf405dd88bfa0e338f7fe4e33cd4d4465eb

**Comment by bcutter** [comment]
What and where is "#e8627cf405dd88bfa0e338f7fe4e33cd4d4465eb" ? Missing reference?
