### ISSUE TITLE
oC 9.1 - 1.1.3: Issues

### ISSUE THREAD

**Issue by mmattel** [icewind1991/logreader#16]
After fresh installing 9.1 and adding logreader 1.1.3, I identified two issues:

1. logreader only shows a white screen and no content
2. the app-drop down list does not dropdown. Therefor you need to go into the browser and correct the url to go back

**Comment by icewind1991** [comment]
anything in the browser log?

**Comment by icewind1991** [comment]
also what browser

**Comment by mmattel** [comment]
Browser tested:
IE11
Opera 38

BTW it seems that the complete top bar is inactive, as I can not even click on my user to eg logout

**Opera Log:**
963 Uncaught SyntaxError: Unexpected token ;
it is the semicolon at ``__proto__"in{};``
```
else t=function(){u.call(r,c)};return function(r){var i={fn:r,next:void 0};n&&(n.next=i),e||(e=i,t()),n=i}}},function(e,t,n){var i=n(9),o=n(4),r=function(e,t){if(o(e),!i(t)&&null!==t)throw TypeError(t+": can't set as prototype!")};e.exports={set:Object.setPrototypeOf||("__proto__"in{};?function(e,t,i)
```

**IE Log:**
SCRIPT1006: ')' erwartet
eee0ebfd7257ae99c1468d7c53981185.js, Zeile: 966, Spalte: 286
```
else t=function(){u.call(r,c)};return function(r){var i={fn:r,next:void 0};n&&(n.next=i),e||(e=i,t()),n=i}}},function(e,t,n){var i=n(9),o=n(4),r=function(e,t){if(o(e),!i(t)&&null!==t)throw TypeError(t+": can't set as prototype!")};e.exports={set:Object.setPrototypeOf||("__proto__"in{};?
```

Seems to be a missing closing bracket

**Comment by icewind1991** [comment]
are you using the asset pipeline?

**Comment by mmattel** [comment]
yes, greatly speeds up interaction...

**Comment by mmattel** [comment]
it worked with 1.1.2 and 9.0.1 having asset pipeline enabled (which is my default setting)

**Comment by icewind1991** [comment]
try disabling the asset pipeline, it's know to mess with some js files

**Comment by mmattel** [comment]
tested with asset pipeline disabled - works
would be great if it also works with an enabled asset pipeline. could you check?

**Comment by icewind1991** [comment]
There isn't much I can do on the apps side, the minifier the asset pipeline uses breaks certain js statements

**Comment by mmattel** [comment]
I remember that we had issues in the past, eg with calendar. Then the issue was raised at https://github.com/tchwork/jsqueeze/issues/39 fixed and merged. Now having the new minifier release also implemented in oC, we can use asset pipelining in oC again...

**Comment by icewind1991** [comment]
Also see https://github.com/nextcloud/server/issues/215

**Comment by mmattel** [comment]
good point, maybe owncloud should do the same...

btw: I once asked if there is a possibility to have minified and non-minified js in parallel and could tag a app to use asset pipelining or not...

**Comment by mmattel** [comment]
I think we can close the issue.
Suggestion: a note at the the apps page and on this readme reagarding problems with asset pipelining would be great.
