### ISSUE TITLE
logreader can not be assigned to groups other than default admin

### ISSUE THREAD

**Issue by mmattel** [icewind1991/logreader#18]
When I tried to assign access to logreader to a group other than admin, access did not work = is not visible for this group members.

**Comment by icewind1991** [comment]
It's hard locked to admins since they are also the only ones that can read the logs normally.

This probably wont change since for nc11 logreader will be moved to be part of the admin settings, so until nc gets a more fine grained admin system this wont change

**Comment by mmattel** [comment]
Thats a pity, nc only or cloud neutral :smile: 
Maybe you could drop a note on the front page...
