### ISSUE TITLE
First line of logfile shows up multiple times

### ISSUE THREAD

**Issue by calis2002** [icewind1991/logreader#3]
OC: 8.1.1
logreader: 1.0.0
Browser: Firefox 40.0.2

When scrolling down to the first logfile entry, this entry gets loaded several times.
When you hold on scrolling this line gets loaded and loaded and loaded...

My owncloud.log (mention reqId z\/9rBXkwqF8UZSiN4UKA which gets loaded several times on the Log reader Page)
![2015_08_27-07_44_24](https://cloud.githubusercontent.com/assets/4539953/9513345/8684d322-4c8f-11e5-8a8b-2f65dfd757cc.png)

Log reader Page
![2015_08_27-07_37_04](https://cloud.githubusercontent.com/assets/4539953/9513298/bc1fb426-4c8e-11e5-992d-eecbc7c5b868.png)

**Comment by icewind1991** [comment]
Fixed with 72d81ddeca60cc924c004d24c53d19118fbc826c

**Comment by icewind1991** [comment]
Pushed a new version to the appstore with the fixes
