### ISSUE TITLE
a few observations

### ISSUE THREAD

**Issue by tessus** [icewind1991/logreader#5]
Great app, but I have a few observations and ideas:

- the app does not save the selection what should be shown. next time I start it, all types of errors are shown again (this could be on purpose, but it would be nice, if the selection could be saved)
- the app should only be available to the admin group by default, otherwise the next item happens
- if a non admin user selects the *Log reader* app, the resulting web page shows a redirect error

**Comment by cdamken** [comment]
> the app does not save the selection what should be shown. next time I start it, all types of errors are shown again (this could be on purpose, but it would be nice, if the selection could be saved)

Nice enhancement :+1:  +1

> the app should only be available to the admin group by default, otherwise the next item happens

You can configure that in which users are available to open the app.

> if a non admin user selects the Log reader app, the resulting web page shows a redirect error

If you block non admin users you don't need this.

**Comment by tessus** [comment]
The `Apps` application is also only available to admins, since only admins can and should be able to install applications. The same is true for the `Log reader` application.

The feature, to choose the groups to which the app is a available to, should not be used to circumvent core requirements. 
Let me explain: if the app were capable of being run by users of all groups, the possibility to restrict the app makes sense. If the app can only be run by a certain group or groups with administrative privileges, enabling the app for certain groups (all groups in the list) makes no sense.
e.g. if the app actually only works when run by an admin, selecting anything else than admin makes no sense. so enabling the app for group admin is a redundant step. also, how should someone know, by which groups the application can be run (except the person who wrote it)?
Do you understand my point?

**Comment by cdamken** [comment]
@tessus Yes, I understand your point and that would be great, but I think that part is not implemented in oC by default, you have to add a group for administrators and there just give the rights.

**Comment by icewind1991** [comment]
> the app should only be available to the admin group by default, otherwise the next item happens

This is fixed in master

**Comment by icewind1991** [comment]
> the app does not save the selection what should be shown. next time I start it, all types of errors are shown again (this could be on purpose, but it would be nice, if the selection could be saved)

Fixed with e7f9be6a71720b89f179f7f6c1804ed993f32ea4

**Comment by icewind1991** [comment]
Pushed a new version to the appstore with the fixes

**Comment by tessus** [comment]
@icewind1991 Thank you. I've re-tested the 3 items and they are fixed.
